### ISSUE TITLE
Safari Session on Iframes

### ISSUE THREAD

**Issue by pochocho** [tsugiproject/tsugi-laravel-sample#3]
Hello After setting up with Laravel 5.5 everything works on chrome and Firefox. But with Safari I get "Session expired - please re-launch" I guess this has to do with the fact that Safari does not allow cross domain cookies, any thoughts on how I might solve this issue?

**Comment by csev** [comment]
Yes - Cookie based sessions are problematic in iframes.

/Chuck

**Comment by pochocho** [comment]
The only work around I can think of is passing the session id through the url, but that opens up the risk of session hijacking. Any pointer you can give me on how you have handled this in the past?

**Comment by csev** [comment]
I pass the session around in the URL in my non-Laraval Tsugi environment - but I work extra hard to catch and stop session hijacking - people past URLs into Facebook :)

There are three ways to go here:

- Go to cookieless sessions - advantage: works great in iframes and in more than one tab at the same time - disadvantage - must add session hijack code

- Use cookie sessions and detect when you are in a frame in JavaScript and force a popup - refuse to be in a frame.

- Go to single page web approach and have the API key (i.e. session) in a JS variable - but then there is not much Laravel left.

None of these options are ideal - for my own tools - I use Tsugi without Laravel and do cookieless sessions because I value iframes and multiple tabs for the best user experience.

/Chuck

**Comment by pochocho** [comment]
Got it. Thanks Charles I appreciate your help.

**Comment by hassantahir01** [comment]
Hi Charles, can you please share the script to catch and stop session hijacking?

**Comment by csev** [comment]
I assume you are talking about cookieless sessions - I have no idea how or if Lavaral handles this.  You can look at the code in to see how I do it.

https://github.com/tsugiproject/tsugi-php/blob/master/src/Core/LTIX.php#L1913

In a sense I use IP address + some browser fingerprinting that I place into the session and if there is a mis-match  I kick them off.  I mask off the last bits of the IP (Class C).
